sources:
  - name: WTFMarketplace
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/hangleang/nft-marketplace-goerli

  - name: NFTs
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/hangleang/nft-goerli

  - name: OpenseaSeaport
    handler:
      jsonSchema:
        endpoint: https://testnets-api.opensea.io/v2/orders/goerli/seaport
        queryParams:
          limit: 10
        operations:
          - type: Query
            field: openseaListings
            path: /listings?token_ids={args.token_ids}&asset_contract_address={args.asset_contract_address}
            method: GET
            responseSample: ./samples/listings.response.json
            responseTypeName: OpenseaListingsResponse
            # argTypeMap:
            #   limit:
            #     type: string
            # queryParamArgMap:
            #   limit: limit
          - type: Query
            field: openseaOffers
            path: /offers?token_ids={args.token_ids}&asset_contract_address={args.asset_contract_address}
            method: GET
            responseSample: ./samples/offers.response.json
            responseTypeName: OpenseaOffersResponse
            # argTypeMap:
            #   limit:
            #     type: string
            # queryParamArgMap:
            #   limit: limit

additionalTypeDefs: |
  extend type Token {
    openseaListings: OpenseaListingsResponse
    openseaOffers: OpenseaOffersResponse
  }

additionalResolvers:
  - targetTypeName: Token
    targetFieldName: openseaListings
    sourceName: OpenseaSeaport # Which source does the target field belong to?
    sourceTypeName: Query # Which root type does the target field belong to?
    sourceFieldName: openseaListings # What is the source field name?
    requiredSelectionSet:
      |
      {
        collection { id }, tokenId
      }
    sourceArgs: # What args does this need to take?
      asset_contract_address: "{root.collection.id}"
      token_ids: "{root.tokenId}"
  - targetTypeName: Token
    targetFieldName: openseaOffers
    sourceName: OpenseaSeaport # Which source does the target field belong to?
    sourceTypeName: Query # Which root type does the target field belong to?
    sourceFieldName: openseaOffers # What is the source field name?
    requiredSelectionSet:
      |
      {
        collection { id }, tokenId
      }
    sourceArgs: # What args does this need to take?
      asset_contract_address: "{root.collection.id}"
      token_ids: "{root.tokenId}"

